im:
  tcpPort: 9001
  webScoketPort: 19001
  bossThreadSize: 1
  workThreadSize: 8
  heartBeatTime: 3000   #心跳超时时间  单位毫秒
  brokerId: 1002  # 用于标识不同的服务器 id值不能相同

  redis:
    mode: single # 单机模式：single哨兵模式：sentinel集群模式：cluster
    database: 0
    password: 123456
    timeout: 3000 #超时时间
    poolMinIdle: 8 #最小空闲数
    poolConnTimeout: 3000 #连接超时时闻（毫秒）
    poolSize: 10 #连接池大小
    single: #redis单机配置
      address: redis://192.168.70.138:6378

  rabbitmq:
    host: 192.168.70.138
    port: 5672
    virtualHost: /
    userName: admin
    password: admin
  zkConfig:
    zkAddr: 192.168.70.138:2181
    zkConnectTimeOut: 5000